site_name: tablespoon
repo_url: https://github.com/alexhallam/tablespoon
theme:
  name: material
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: pink
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: purple
  icon:
    repo: fontawesome/brands/git-alt
  features:
    - navigation.indexes
    - navigation.tracking
    - navigation.instant
    - navigation.sections
    - navigation.expand

nav:
  - API: section/api.md
  - Math: section/math.md
  - Example Code:
      - Simple Example: section/plotting.md
      - Extended Example: section/extended.md
      - Skill Score Example: section/skill.md
      - Parallel Computing Example: section/parallel.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

plugins:
  - mkdocstrings
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
